version: '3.8'

services:
  docker-cleanup:
    read_only: true
    container_name: cleaner
    build: .
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
