version: '3.9'

services:
  docker-cleanup:
    container_name: cleaner
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - "no-new-privileges:true"
