version: '3.8'

services:
  docker-cleanup:
    read_only: true
    container_name: cleaner
    build: .
    restart: any
    cpus: '0.2'
    mem_limit: 200M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

networks:
  web:
    name: cleaner_web
