version: '3.8'

services:
  docker-cleanup:
    container_name: cleaner
    build: .
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

networks:
  web:
    name: cleaner_web
